// Bundled fallback voice catalog (Deepgram Aura-2, verified against /v1/models).
// The options page can refresh the full live catalog (100+ voices) with your API key.
const BRAUO_FALLBACK_VOICES = [
  // Spanish
  { model: "aura-2-celeste-es", name: "Celeste", lang: "es-CO" },
  { model: "aura-2-gloria-es", name: "Gloria", lang: "es-CO" },
  { model: "aura-2-estrella-es", name: "Estrella", lang: "es-MX" },
  { model: "aura-2-javier-es", name: "Javier", lang: "es-MX" },
  { model: "aura-2-luciano-es", name: "Luciano", lang: "es-MX" },
  { model: "aura-2-olivia-es", name: "Olivia", lang: "es-MX" },
  { model: "aura-2-sirio-es", name: "Sirio", lang: "es-MX" },
  { model: "aura-2-valerio-es", name: "Valerio", lang: "es-MX" },
  { model: "aura-2-agustina-es", name: "Agustina", lang: "es-ES" },
  { model: "aura-2-alvaro-es", name: "Álvaro", lang: "es-ES" },
  { model: "aura-2-carina-es", name: "Carina", lang: "es-ES" },
  { model: "aura-2-diana-es", name: "Diana", lang: "es-ES" },
  { model: "aura-2-nestor-es", name: "Néstor", lang: "es-ES" },
  { model: "aura-2-silvia-es", name: "Silvia", lang: "es-ES" },
  { model: "aura-2-antonia-es", name: "Antonia", lang: "es-AR" },
  { model: "aura-2-aquila-es", name: "Aquila", lang: "es-419" },
  { model: "aura-2-selena-es", name: "Selena", lang: "es-419" },
  // English
  { model: "aura-2-thalia-en", name: "Thalia", lang: "en-US" },
  { model: "aura-2-asteria-en", name: "Asteria", lang: "en-US" },
  { model: "aura-2-apollo-en", name: "Apollo", lang: "en-US" },
  { model: "aura-2-arcas-en", name: "Arcas", lang: "en-US" },
  { model: "aura-2-athena-en", name: "Athena", lang: "en-US" },
  { model: "aura-2-atlas-en", name: "Atlas", lang: "en-US" },
  { model: "aura-2-aurora-en", name: "Aurora", lang: "en-US" },
  { model: "aura-2-helena-en", name: "Helena", lang: "en-US" },
  { model: "aura-2-luna-en", name: "Luna", lang: "en-US" },
  { model: "aura-2-orion-en", name: "Orion", lang: "en-US" },
  { model: "aura-2-zeus-en", name: "Zeus", lang: "en-US" },
  { model: "aura-2-andromeda-en", name: "Andromeda", lang: "en-US" },
  { model: "aura-2-draco-en", name: "Draco", lang: "en-GB" },
  { model: "aura-2-pandora-en", name: "Pandora", lang: "en-GB" },
  { model: "aura-2-hyperion-en", name: "Hyperion", lang: "en-AU" },
  { model: "aura-2-theia-en", name: "Theia", lang: "en-AU" },
  { model: "aura-2-amalthea-en", name: "Amalthea", lang: "en-PH" },
  // German
  { model: "aura-2-aurelia-de", name: "Aurelia", lang: "de-DE" },
  { model: "aura-2-elara-de", name: "Elara", lang: "de-DE" },
  { model: "aura-2-fabian-de", name: "Fabian", lang: "de-DE" },
  { model: "aura-2-julius-de", name: "Julius", lang: "de-DE" },
  { model: "aura-2-kara-de", name: "Kara", lang: "de-DE" },
  { model: "aura-2-lara-de", name: "Lara", lang: "de-DE" },
  { model: "aura-2-viktoria-de", name: "Viktoria", lang: "de-DE" },
  // French
  { model: "aura-2-agathe-fr", name: "Agathe", lang: "fr-FR" },
  { model: "aura-2-hector-fr", name: "Hector", lang: "fr-FR" },
  // Italian
  { model: "aura-2-cesare-it", name: "Cesare", lang: "it-IT" },
  { model: "aura-2-cinzia-it", name: "Cinzia", lang: "it-IT" },
  { model: "aura-2-demetra-it", name: "Demetra", lang: "it-IT" },
  { model: "aura-2-dionisio-it", name: "Dionisio", lang: "it-IT" },
  { model: "aura-2-elio-it", name: "Elio", lang: "it-IT" },
  { model: "aura-2-flavio-it", name: "Flavio", lang: "it-IT" },
  { model: "aura-2-livia-it", name: "Livia", lang: "it-IT" },
  { model: "aura-2-maia-it", name: "Maia", lang: "it-IT" },
  { model: "aura-2-melia-it", name: "Melia", lang: "it-IT" },
  // Japanese
  { model: "aura-2-ama-ja", name: "Ama", lang: "ja-JP" },
  { model: "aura-2-ebisu-ja", name: "Ebisu", lang: "ja-JP" },
  { model: "aura-2-fujin-ja", name: "Fujin", lang: "ja-JP" },
  { model: "aura-2-izanami-ja", name: "Izanami", lang: "ja-JP" },
  { model: "aura-2-uzume-ja", name: "Uzume", lang: "ja-JP" },
  // Dutch
  { model: "aura-2-beatrix-nl", name: "Beatrix", lang: "nl-NL" },
  { model: "aura-2-cornelia-nl", name: "Cornelia", lang: "nl-NL" },
  { model: "aura-2-daphne-nl", name: "Daphne", lang: "nl-NL" },
  { model: "aura-2-hestia-nl", name: "Hestia", lang: "nl-NL" },
  { model: "aura-2-lars-nl", name: "Lars", lang: "nl-NL" },
  { model: "aura-2-leda-nl", name: "Leda", lang: "nl-NL" },
  { model: "aura-2-rhea-nl", name: "Rhea", lang: "nl-NL" },
  { model: "aura-2-roman-nl", name: "Roman", lang: "nl-NL" },
  { model: "aura-2-sander-nl", name: "Sander", lang: "nl-NL" }
];
